name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Simulate failed deployment
        id: deploy_attempt
        run: |
          echo "::set-output name=error::Error: User must have access to the project to create deployments"
        
      - name: Test Action
        uses: ./
        with:
          vercel-token: ${{ secrets.TEST_VERCEL_TOKEN }}
          project-path: './test-project'
          deployment-error: ${{ steps.deploy_attempt.outputs.error }}

      - name: Verify deployment attempt
        run: |
          if [[ -f "deployment_attempted" ]]; then
            echo "Action responded to authorization error"
          else
            echo "Action did not respond correctly"
            exit 1
          fi